### ISSUE TITLE
Php 7.4+

### ISSUE THREAD

**Issue by nglez03** [FacturaPuntoCom/PrestaShoppCFDI33_1.7#7]
Actualizar el soporte para PHP 7.4 en adelante. Ya que no se puede enlazar al menu desde el back office de prestashop.

**Comment by eduardofactura** [comment]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/82902993/176470242-63b7a521-ece1-4abd-8bab-a76aab6ed092.png">

La versión de prestashop 1.7 no es compatible con php 7.4

**Comment by FacturaPuntoCom** [comment]
Hola FacturaPuntoCom/PrestaShoppCFDI33_1.7!

Gracias por tu mensaje. Nuestro equipo le responderá en breve y lo
actualizaremos por correo electrónico.

Puedes dar seguimiento a tu petición con nosotros en cualquier
momento Centro de ayuda factura.com
[https://soporte.factura.com/conversation/view/102604].

Saludos! 

Este es un mensaje Factura.com enviado por Kayako
[https://kayako.com].
